/**
 * Compatibility entry point. New persistence code belongs in repositories/;
 * keep existing callers working without exposing internal storage state here.
 */
export {
  LocalPersistenceWriteError,
  getDb,
  getLocalPromptLineageState,
  getLocalPromptLineageStateForStory,
  getLocalPromptCompilationHeadsForStory,
  replaceLocalPromptLineageState,
  resetMemoryStateForTesting,
} from "./repositories/runtime";
export { upsertUser, getUserByOpenId, getUserById } from "./repositories/users";
export {
  type AccessOverviewRow,
  recordAccessHeartbeat,
  getAccessOverview,
} from "./repositories/accessAnalytics";
export {
  createProject,
  getOrCreateUserDefaultProject,
  getUserProjects,
  getProjectById,
} from "./repositories/projects";
export {
  createReference,
  getProjectReferences,
  updateReference,
} from "./repositories/references";
export {
  createShots,
  replaceDirectorShotsForStory,
  getProjectShots,
  getStoryShots,
  updateShot,
  batchUpdateShots,
} from "./repositories/shots";
export {
  createAnalysisResult,
  getProjectAnalysis,
} from "./repositories/analysis";
export {
  getEmotionAnalysisProfile,
  upsertEmotionAnalysisProfile,
  getEmotionDailyLetter,
  listEmotionDailyLetters,
  ensureEmotionDailyLetter,
  upsertEmotionDailyLetter,
  updateEmotionDailyLetterIfRevision,
} from "./repositories/emotionLetters";
export {
  type StoryListItem,
  storyActivityDates,
  listUserStories,
  findShiguangImportedStory,
  listUserStorySummariesPage,
  getStoryById,
  createStory,
  updateStory,
  writeStoryTitle,
  updateStoryBodyIfRevision,
} from "./repositories/stories";
export {
  deleteStory,
  type LegacyGuestClaimResult,
  claimLegacyGuestStories,
  claimGuestStories,
} from "./repositories/storyLifecycle";
export {
  getGeneratedImageById,
  getStoryImages,
  getProjectGeneratedImages,
  getStoryGeneratedImages,
  getGeneratedImageByStoryAndImageKey,
  createImageSignal,
  promoteStoryImageToCurrent,
  assignStoryImageToShot,
  getImageSignalsForImages,
  getRecentRejectionSignals,
  getRecentChatCorrections,
  createGeneratedImage,
  deleteGeneratedImage,
  updateImageCurrent,
  reassignImage,
} from "./repositories/images";
export {
  createEditSnapshot,
  getLatestEditSnapshot,
  getRecentEditSnapshots,
  getEditSnapshotById,
  createSemanticAnnotation,
  getAnnotationsBySnapshotId,
  getRecentSemanticAnnotations,
  getRecentEditPreferences,
} from "./repositories/editHistory";
export {
  TIMELINE_FRAME_EXTRACTION_DAILY_RECEIPT_LIMIT,
  TIMELINE_FRAME_EXTRACTION_USER_RECEIPT_LIMIT,
  TIMELINE_FRAME_EXTRACTION_STORY_RECEIPT_LIMIT,
  assertTimelineFrameExtractionReceiptQuota,
  getTimelineFrameExtractionOperation,
  claimTimelineFrameExtractionOperation,
  renewTimelineFrameExtractionClaim,
  recordTimelineFrameExtractionDescriptor,
  releaseTimelineFrameExtractionClaim,
  failTimelineFrameExtractionOperation,
  settleTimelineFrameExtractionAsset,
  markTimelineFrameExtractionSucceeded,
} from "./repositories/frameExtractions";
export {
  getPreviewMaskedImageOperation,
  getSucceededPreviewMaskedImageOperationForCandidate,
  getLatestSucceededPreviewMaskedImageOperationForTarget,
  claimPreviewMaskedImageOperation,
  markPreviewMaskedImageOperationAccepted,
  failPreviewMaskedImageOperation,
  settlePreviewMaskedImageOperationSuccess,
} from "./repositories/maskedImageOperations";
export {
  createVideoTake,
  updateVideoTake,
  updateVideoTakeRangesShotIdentity,
  getVideoTakeById,
  getStoryVideoTakes,
  getReusableVideoTakesForStory,
  findVideoTakeByIdempotencyKey,
  createVideoTakeIdempotently,
  type EditingTransitionSubmissionClaim,
  claimEditingTransitionSubmission,
  type StartEndShotSubmissionClaim,
  claimStartEndShotSubmission,
  createVideoTakeRange,
  getStoryVideoTakeRanges,
  getVideoTakeRangeById,
  getStoryVideoTimelineSelections,
  setVideoTimelineSelection,
  clearVideoTimelineSelection,
} from "./repositories/videos";
export {
  getStoryTimeline,
  updateStoryTimeline,
  updateStoryAndTimelineAtomic,
  applyStoryTimelineOverlayAtomic,
  applyGeneratedVisualShotAtomic,
  insertTransitionShotAtomic,
  restoreSplitStoryShotAtomic,
} from "./repositories/timelines";
export {
  removeManagedAudioFiles,
  type StoryAudioAssetPatch,
  createStoryAudioAssetRow,
  updateStoryAudioAssetRow,
  getStoryAudioAssetRow,
  listStoryAudioAssetRows,
  listStoryAudioAssetRowsForUser,
  findReusableStoryAudioAssetRow,
  type StoryAudioImportOperationPatch,
  type StoryAudioImportBundleResult,
  createStoryAudioImportBundle,
  createStoryAudioImportOperationRow,
  getStoryAudioImportOperationRow,
  updateStoryAudioImportOperationRow,
  listUnsettledStoryAudioImportOperationRows,
  listStoryAudioStorageKeysForStory,
} from "./repositories/audioAssets";
export {
  createShotDerivationDraft,
  getShotDerivationDraft,
  updateShotDerivationDraft,
  createStoryOperation,
  getStoryOperation,
  markStoryOperationReverted,
  confirmDerivedShotAtomic,
  undoDerivedShotAtomic,
} from "./repositories/shotDerivations";
export {
  seedProjectForTesting,
  seedStoryForTesting,
  serializeStorySoundDirectorStateForTesting,
  restoreStorySoundDirectorStateForTesting,
} from "./repositories/testing";
export {
  getStorySoundWorkspaceRecord,
  compareAndSaveStorySoundWorkspaceRecord,
  listStorySoundPlanVersionRecords,
  getStorySoundPlanVersionRecord,
  getOrCreateStorySoundPlanVersionRecord,
  getOrCreateStorySoundRowOperationRecord,
  listStorySoundRowOperationRecords,
  upsertStoryVoiceProfileRecord,
  getStoryVoiceProfileRecord,
  getOrCreateStoryVoiceActivationOperationRecord,
} from "./repositories/soundPlans";
export {
  createEmailOtp,
  findValidEmailOtp,
  markEmailOtpUsed,
  type InviteOverviewRow,
  getInviteOverview,
  createInviteCode,
  findAvailableInviteCode,
  findInviteCodeForEmailAccess,
  hasRedeemedInviteForEmail,
  redeemInviteForEmail,
  bindRedeemedInviteToUser,
} from "./repositories/invites";
export {
  type CreditAccountSummary,
  getCreditAccountSummary,
  type ReserveComputeCreditInput,
  type ReserveComputeCreditResult,
  reserveComputeCredit,
  type ApplyComputeSettlementInput,
  type ApplyComputeSettlementResult,
  applyComputeSettlement,
  type AppendCreditEntryInput,
  type AppendCreditEntryResult,
  appendCreditLedgerEntry,
  listCreditLedgerEntries,
  findBillingOperation,
  type ComputeStatementSnapshot,
  type ComputeStatementSnapshotInput,
  readComputeStatementSnapshot,
  findActiveCreditHold,
  type RecordProviderAttemptInput,
  recordProviderAttempt,
  listProviderAttemptsForOperation,
} from "./repositories/computeLedger";
export {
  normalizeAccountEmail,
  type EmailIdentityResolution,
  resolveEmailIdentity,
  linkEmailIdentity,
  type LoginIdentityProvider,
  getLoginIdentity,
  linkLoginIdentity,
  getPasswordCredential,
  setPasswordCredential,
  getUserSessionVersion,
  bumpUserSessionVersion,
  type VerificationChallengeInput,
  issueVerificationChallenge,
  type ChallengeConsumption,
  consumeVerificationChallenge,
  type RateLimitDecision,
  type PairingRedemption,
  issueDevicePairingCode,
  consumeDevicePairingCode,
  consumePersistentRateLimit,
} from "./repositories/accounts";
export {
  type PersonalMemoryEventRow,
  type PersonalMemoryMysqlTx,
  type PersonalMemoryTxScope,
  capturePersonalMemoryEvent,
  capturePersonalMemoryEventStandalone,
  getPersonalMemoryEventByIdentity,
  listPersonalMemoryEvents,
  listPersonalMemoryEventsPage,
  listPersonalMemoryEventsByIds,
  listPersonalMemoryEventsForDay,
  listPersonalMemoryInsightsForUser,
  listPersonalMemoryInsightsByIds,
  projectPersonalMemoryOutboxIntoIndex,
  getPersonalMemoryPrivacyEpoch,
  bumpPersonalMemoryPrivacyEpoch,
} from "./repositories/memoryEvents";
export {
  type AppendDailyLetterVersionInput,
  type AppendDailyLetterVersionResult,
  appendEmotionDailyLetterVersion,
  saveEmotionDailyLetterMessageIfRevision,
  listEmotionDailyLetterVersions,
  listPersonalMemoryLetterVersionsByIds,
  type BeginPersonalMemoryLetterAttemptInput,
  type BeginPersonalMemoryLetterAttemptResult,
  beginPersonalMemoryLetterAttempt,
  type CommitPersonalMemoryLetterAttemptInput,
  type CommitPersonalMemoryLetterAttemptResult,
  commitPersonalMemoryLetterAttempt,
  failPersonalMemoryLetterAttempt,
  getPersonalMemoryLetterAttemptById,
  drainLocalPersonalMemoryOutbox,
} from "./repositories/memoryLetters";
export {
  type PersonalMemoryInsightRow,
  type ClaimPersonalMemoryJobsInput,
  claimPersonalMemoryJobs,
  type PersonalMemoryExtractionCompletion,
  type PersonalMemoryAppliedMutation,
  type PersonalMemoryExtractionCompletionResult,
  completePersonalMemoryExtractionJob,
  type FailPersonalMemoryJobInput,
  failPersonalMemoryJob,
  countPendingPersonalMemoryJobs,
  listActivePersonalMemoryInsightCandidates,
  isPersonalMemoryEventSuppressed,
  listPersonalMemoryInsightLineage,
  listPersonalMemoryEvidenceForInsight,
  type LineageStateChangeResult,
  archivePersonalMemoryInsightLineage,
  restorePersonalMemoryInsightLineage,
  forgetPersonalMemoryInsightLineage,
  type ScrubEventResult,
  scrubPersonalMemoryEventAndRecompute,
  correctPersonalMemoryInsight,
  getPersonalMemorySuppression,
  getChatMessageContentForPersonalMemory,
  getPersonalMemoryEventById,
} from "./repositories/memoryInsights";
export { TIMELINE_FRAME_EXTRACTION_QUOTA_ERROR } from "./persistence/timelineFrameExtractionErrors";
export type {
  EditSnapshot,
  SemanticAnnotation,
  GeneratedImage,
} from "../drizzle/schema";
